### ISSUE TITLE
Polygott Docker images error in kubernetes ?

### ISSUE THREAD

**Issue by znyrsam** [replit/polygott#271] opened 2021-09-13 14:01 UTC
Polygott Docker Image - replco/polygott:c82c08a720ba1fd537d4fba17eed883ab87c0fd7
Docker image link - https://hub.docker.com/layers/replco/polygott/c82c08a720ba1fd537d4fba17eed883ab87c0fd7/images/sha256-03f1f7c5d0d66ded71ca20c5b64e56f43029c745265f55d32d5c6f685bd50f31?context=explore
Whenever we deploy the yaml file using this docker image showing this error :

gcstest   0/1     CrashLoopBackOff   10         56m

detail error :

  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  48m                   default-scheduler  Successfully assigned default/gcstest to gke-cluster-2-default-pool-cc1f421b-0k6g
  Normal   Pulling    48m                   kubelet            Pulling image "replco/polygott:c82c08a720ba1fd537d4fba17eed883ab87c0fd7"
  Normal   Pulled     18m                   kubelet            Successfully pulled image "replco/polygott:c82c08a720ba1fd537d4fba17eed883ab87c0fd7" in 29m58.832592007s
  Normal   Created    17m (x5 over 18m)     kubelet            Created container gcstest
  Normal   Started    17m (x5 over 18m)     kubelet            Started container gcstest
  Normal   Pulled     17m (x4 over 18m)     kubelet            Container image "replco/polygott:c82c08a720ba1fd537d4fba17eed883ab87c0fd7" already present on machine
  Warning  BackOff    3m45s (x71 over 18m)  kubelet            Back-off restarting failed container

**Comment by lhchavez** [comment] 2021-09-13 14:24
yikes, this was never intended to work in k8s :S there's no [`COMMAND` or `ENTRYPOINT`](https://hub.docker.com/layers/replco/polygott/latest/images/sha256-03f1f7c5d0d66ded71ca20c5b64e56f43029c745265f55d32d5c6f685bd50f31?context=explore) in the image (you need to provide your own), so that should explain the crashloop.

i'm closing this since it's working as intended and completely unsupported. maybe reach out [in the discord](https://replit.com/discord) to see if any other community member can help out.

**Closed by lhchavez** 2021-09-13 14:24 UTC
